-- Sequences for Pharmacy Management System

CREATE SEQUENCE seq_category START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_supplier START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_medicine START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_batch START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE seq_customer START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE seq_doctor START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE seq_prescription START WITH 4001 INCREMENT BY 1;
CREATE SEQUENCE seq_prescription_item START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_bill START WITH 9001 INCREMENT BY 1;
CREATE SEQUENCE seq_bill_item START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_stock_audit START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_reorder_alert START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_expired_log START WITH 1 INCREMENT BY 1;
